uploading new yml

diff --git a/.github/workflows/azure-static-web-apps-brave-pebble-0b1e93303.yml b/.github/workflows/azure-static-web-apps-brave-pebble-0b1e93303.yml
--- a/.github/workflows/azure-static-web-apps-brave-pebble-0b1e93303.yml
+++ b/.github/workflows/azure-static-web-apps-brave-pebble-0b1e93303.yml
@@ -1,45 +1,142 @@
-name: Azure Static Web Apps CI/CD
+name: Publish Wiki to Azure Static Web App
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    types: [opened, synchronize, reopened, closed]
-    branches:
-      - main
+on: 
+  gollum
 
 jobs:
   build_and_deploy_job:
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
     runs-on: ubuntu-latest
     name: Build and Deploy Job
     steps:
-      - uses: actions/checkout@v2
+      - name: checkout wiki
+        uses: actions/checkout@v3
         with:
-          submodules: true
+          repository: ${{github.repository}}.wiki
+          path: 'docs'
+      - name: configureing prerequisites
+        run:  |
+          pip install mkdocs mkdocs-exclude
+      - name: parse file tags
+        run: |
+          # find config file
+          for file in $(find ./docs/ -name "*.md")
+          do
+            # check if file has config tag
+            if [ "$(sed -n -e '1{/<\!-- hasConfig -->/p}' "$file")" ]; then
+              configfile=$file
+            fi
+          done
+
+          if [ "$configfile" ]; then
+            echo "CONFIG_SOURCE_FILE=$configfile" >> $GITHUB_ENV
+            echo "::notice ::Config read from wiki page $configfile"
+          else
+            echo '::error ::no file found with tag <\!-- hasConfig -->  on first line. add config codeblocks and tag.'
+            exit 1
+          fi
+
+
+          excludeFromPublish=''
+          for file in $(find ./docs/ -name "*.md")
+          do
+            wikiFilePath=$(realpath --relative-to ./docs "$file")
+
+            #check if file has do not publish tag
+            if [ "$(sed -n -e '1{/<\!-- doNotPublish -->/p}' "$file")" ]; then
+              excludeFromPublish="$excludeFromPublish:$wikiFilePath"
+            fi
+          done  
+          echo "::notice ::Pages excluded from publishing: [${excludeFromPublish:1}]"
+          echo "EXCLUDE_GLOBS=${excludeFromPublish:1}" >> $GITHUB_ENV
+      - name: build mkdocs config
+        env:
+          BASE_CONFIG_FILE: base.yml
+          CONFIG_FILE: mkdocs.yml
+          REPO_URL: https://github.com/${{github.repository}}/wiki
+        run: |
+          # read config from config source file in wiki
+          config=$(sed -n '/^```mkdocs.yml$/,/^```$/p' "$CONFIG_SOURCE_FILE")
+          if [ ! "$config" ]; then
+            echo "::error ::no codeblock found marked with 'mkdocs.yml' in file '$CONFIG_SOURCE_FILE'."
+            exit 1
+          fi
+          echo "$config" | sed '/^```/d' > "$BASE_CONFIG_FILE"
+
+          # build extended mkdocs config for publishing
+          echo ''                             >  "$CONFIG_FILE"
+
+          #inherit from parsed config
+          echo "INHERIT: ./$BASE_CONFIG_FILE" >> "$CONFIG_FILE"
+          echo "repo_url: $REPO_URL"          >> "$CONFIG_FILE"
+          echo "edit_uri: ''"                 >> "$CONFIG_FILE"
+
+          # add files to exclude from deployment
+          echo "plugins:"                     >> "$CONFIG_FILE"
+          echo "  - exclude:"                 >> "$CONFIG_FILE"
+          echo "      glob: "                 >> "$CONFIG_FILE"
+
+          IFS=':' read -ra GLOBS <<< "$EXCLUDE_GLOBS"
+          for glob in "${GLOBS[@]}"; do 
+            echo "        - \"$glob\""  >> "$CONFIG_FILE"
+          done
+      - name: add page title to content
+        run: |
+          # foreach file parse the title and include in frontmatter as title.
+          # for more information on title parsing: https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data 
+          for file in $(find ./docs/ -name '*.md')
+          do
+            filename=$(basename -- "$file")
+            title=$(echo "${filename%.*}" | tr '-' ' ')
+            echo "filename $filename -> $title"   
+
+            echo -e "Title: $title\n\n$(cat $file)" > "$file"
+          done
+      - name: rename homepage to index.md
+        run:  |
+          # find homepage codeblock in config source file
+          homepage=$(sed -n '/^```homepage$/,/^```$/p' "$CONFIG_SOURCE_FILE" | sed '/^```/d')
+          if [ ! "$homepage" ]; then
+            echo "::error ::no codeblock found marked with `homepage` in file `$CONFIG_SOURCE_FILE`."
+            exit 1
+          else
+            echo "::notice ::Homepage created from $homepage"
+          fi
+
+          if [[ ! -f ./docs/index.md ]]; then 
+            find ./docs/ -maxdepth 1 -iname "$homepage" -exec mv {} ./docs/index.md \;
+          fi
+      - name: replace links to homepage with index.md
+        run: |
+          homepage=$(sed -n '/^```homepage$/,/^```$/p' "$CONFIG_SOURCE_FILE" | sed '/^```/d')
+          homepagelink="${homepage%.*}"
+          
+          for file in $(find ./docs/ -name '*.md')
+          do
+             # replace '[linkname](homepagefile)' with '[linkname](index)'
+             sed -i "s/]($homepagelink)/](index.md)/g" $file
+          done
+      - name: build site
+        run: mkdocs build
+      - name: build static web app config
+        env:
+          STATIC_CONFIG_FILE: site/staticwebapp.config.json
+        run: |
+          # read config from config source file in wiki
+          staticapp_config=$(sed -n '/^```staticwebapp.config.json$/,/^```$/p' "$CONFIG_SOURCE_FILE")
+          if [ ! "$staticapp_config" ]; then
+            echo "::error ::no codeblock found marked with 'staticwebapp.config.json' in file '$CONFIG_SOURCE_FILE'."
+            exit 1
+          fi
+          echo "$staticapp_config" | sed '/^```/d' > "$STATIC_CONFIG_FILE"
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
         with:
-          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_PEBBLE_0B1E93303 }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
+          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
+          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
           action: "upload"
-          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
-          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
-          app_location: "/" # App source code path
-          api_location: "" # Api source code path - optional
-          output_location: "" # Built app content directory - optional
+          ###### Repository/Build Configurations ######
+          app_location: "site" # App source code path relative to repository root
+          skip_app_build: true
+          skip_api_build: true
           ###### End of Repository/Build Configurations ######
-
-  close_pull_request_job:
-    if: github.event_name == 'pull_request' && github.event.action == 'closed'
-    runs-on: ubuntu-latest
-    name: Close Pull Request Job
-    steps:
-      - name: Close Pull Request
-        id: closepullrequest
-        uses: Azure/static-web-apps-deploy@v1
-        with:
-          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_PEBBLE_0B1E93303 }}
-          action: "close"
